# Generated by Django 3.0.3 on 2020-02-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20200217_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
